export enum CertificateExtension {
    BASIC_CONSTRAINT = 'BASIC_CONSTRAINT',
    DIGITAL_SIGNATURE = 'DIGITAL_SIGNATURE',
    HTTPS = 'HTTPS',
    SUBJECT_ALTERNATIVE_NAME = 'SUBJECT_ALTERNATIVE_NAME',
    SUBJECT_KEY_IDENTIFIER = 'SUBJECT_KEY_IDENTIFIER'

    //promeni sta treba ovde
  }